/**
 * Environment shape for the edge Worker.
 *
 * `Env` is generated by `wrangler types` from wrangler.jsonc. `EDGE_SERVICE_KEY` is a secret set with
 * `wrangler secret put EDGE_SERVICE_KEY --env <env>`; it never appears in configuration files.
 */
export type EdgeEnv = Env & {
  EDGE_SERVICE_KEY?: string;
};

export type FeatureFlag =
  | "SUPERVISION_ENABLED"
  | "AUTO_RECOVERY_ENABLED"
  | "READ_CACHE_ENABLED"
  | "BROWSER_DIAGNOSTICS_ENABLED";

/** A flag is on only when its value is exactly the string "true". Anything else is off. */
export function flagEnabled(env: EdgeEnv, flag: FeatureFlag): boolean {
  return env[flag] === "true";
}

export function intVar(value: string | undefined, fallback: number): number {
  if (value === undefined) return fallback;
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : fallback;
}

export const SESSION_COOKIE = "buddy_view";
export const SCOPE_COOKIE = "buddy_scope";
export const EDGE_KEY_HEADER = "X-Buddy-Edge-Key";
export const EDGE_SESSION_HEADER = "X-Buddy-Edge-Session";
